### ISSUE TITLE
This game throws an error and doesn't load

### ISSUE THREAD

**Issue by AmasaDelano** [Vagabottos/RootVis#23]
[https://raw.githubusercontent.com/Vagabottos/Rootlog/master/Games/2020_11_19_winter_tournament_r1g2.rootlog](https://raw.githubusercontent.com/Vagabottos/Rootlog/master/Games/2020_11_19_winter_tournament_r1g2.rootlog)

I can't get the error to be thrown on my local machine, for some reason.

**Comment by seiyria** [comment]
Looks like a lot of forests are busted! I'll look.
