### ISSUE TITLE
Display players in sidebar in turn order, with first player first

### ISSUE THREAD

**Issue by AmasaDelano** [Vagabottos/RootVis#28]
Not entirely sure how turn order can be determined, but it's not the same as draft order (the order the players are in at the beginning).

**Comment by seiyria** [comment]
Turn order would be able to be determined by doing a loop through the actions, checking the turn player prop, and stopping when you hit a duplicate. Then you can hold onto that array and iterate over that instead of the keyval for the player sidebar.
