### ISSUE TITLE
Display battle indicator by a clearing when the battle action is occurring

### ISSUE THREAD

**Issue by AmasaDelano** [Vagabottos/RootVis#31]
Root being a sort of a war game, this seems like a high-value, exciting enhancement to make, whenever we get around to it.

**Comment by seiyria** [comment]
I like this! I know just the way to do it too.

**Comment by seiyria** [comment]
![image](https://user-images.githubusercontent.com/763609/102354609-6c40b880-3f70-11eb-9a92-1bdae91eabc5.png)
